优化代码

diff --git a/android/hooks/pre-commit b/android/hooks/pre-commit
--- a/android/hooks/pre-commit
+++ b/android/hooks/pre-commit
@@ -1,26 +1,22 @@
-#!/bin/sh
+#!/bin/bash
 
-cd android
+cd android || return
 ./gradlew spotlessCheck
 result=$?
-cd ..
-printf "the spotlessCheck result code is $result"
-if [[ "$result" = 0 ]] ; then
-    echo "\033[32m
-    ....
-    SpotlessCheck Pass!!
-    ....
-    \033[0m"
-    exit 0
-else
-    ./gradlew spotlessApply
-    echo "\033[31m
-    ....
-    SpotlessCheck Failed!!
-    代码格式有问题;
-    ....
-    已经自动调整格式,review代码后再git add . && git commit
-    ....
-    \033[0m"
+printf "the spotlessCheck result code is %s." "$result"
+if [[ "$result" = 0 ]]; then
+  printf "SpotlessCheck Pass!\n"
+  ./gradlew detekt
+  result=$?
+  printf "the DetektCheck result code is %s." "$result"
+  if [[ "$result" = 0 ]]; then
+    printf "DetektCheck Pass!\n"
+  else
+    printf "DetektCheck Failed!\n"
     exit 1
+  fi
+else
+  printf "SpotlessCheck Failed!\n"
+  exit 1
 fi
+cd ..
